name: my_fuel
description: "تطبيق وقودي من شركة MU-CODE."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ========== Core Dependencies ==========
  # State Management
  get: ^4.7.2

  # ========== Firebase Services ==========
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  webview_flutter_plus: ^0.4.19

  # ========== UI & Design ==========
  ## Layout & Styling
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  auto_animated: ^3.2.0
  cupertino_icons: ^1.0.8

  # Flutter localizations SDK)
  flutter_localizations:
    sdk: flutter

  flutter_holo_date_picker: ^2.0.0
  date_picker_plus: ^4.2.0
  ## UI Components
  another_carousel_pro: ^1.0.2
  flutter_otp_text_field: ^1.5.1+1
  pretty_qr_code: ^3.4.0
  country_picker: ^2.0.27

  # ========== Device Features ==========
  mobile_scanner: ^6.0.7
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  camera: ^0.11.2

  # ========== Data & Storage ==========
  get_storage: ^2.1.1
  syncfusion_flutter_datagrid: ^30.1.40
  syncfusion_flutter_pdf: ^30.1.40

  # ========== Utilities ==========
  ## Networking
  http: ^1.3.0
  dio: ^5.8.0+1

  ## Localization
  intl: ^0.20.2

  ## System
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  open_filex: ^4.7.0
  image_gallery_saver_plus: ^4.0.1

  ## Notifications
  flutter_local_notifications: ^19.3.1
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dependency_validator: ^3.2.0

  # Development-only packages
  excel: ^4.0.6
  http_parser: ^4.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/translations/ar_AR.json
    - assets/translations/en_US.json
    - assets/images/user_avatar.png
    - assets/images/logo.png
    - assets/animations/loading.gif
    - assets/images/fuel_icon.svg
    - assets/slides fuels/1.jpg
    - assets/slides fuels/2.jpg
    - assets/slides fuels/3.jpg
    - assets/slides fuels/4.jpg
    - assets/slides fuels/5.jpg
    - assets/slides fuels/6.jpg
    - assets/slides fuels/7.jpg
    - assets/slides fuels/8.jpg
    - assets/slides fuels/9.jpg
    - assets/slides fuels/10.jpg

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf
          weight: 700
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria-VariableFont_wght.ttf
